name: Deploy to EC2

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Install Gradle 8.5
        run: |
          wget -q https://services.gradle.org/distributions/gradle-8.5-bin.zip
          unzip -q gradle-8.5-bin.zip
          export PATH=$PWD/gradle-8.5/bin:$PATH
          echo "PATH=$PWD/gradle-8.5/bin:$PATH" >> $GITHUB_ENV
          gradle --version

      - name: Build with Gradle
        run: gradle build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/orders-canceler:latest,${{ secrets.DOCKERHUB_USERNAME }}/orders-canceler:${{ github.sha }}
          no-cache: true

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          timeout: 180s
          command_timeout: 20m
          debug: true
          script: |
            # Instalar Docker si no está instalado
            if ! command -v docker &> /dev/null; then
              echo "Docker no está instalado. Instalando Docker..."
              sudo apt-get update
              sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
              sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
              sudo apt-get update
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker $USER
              echo "Docker instalado correctamente"
            fi
            
            # Verificar que Docker esté en ejecución
            if ! sudo systemctl is-active --quiet docker; then
              echo "Docker no está en ejecución. Iniciando Docker..."
              sudo systemctl start docker
            fi
            
            # Instalar Docker Compose si no está instalado
            if ! command -v docker-compose &> /dev/null; then
              echo "Docker Compose no está instalado. Instalando Docker Compose..."
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              echo "Docker Compose instalado correctamente"
            fi
            
            # Verificar versiones de Docker y Docker Compose
            sudo docker --version
            docker-compose --version
            
            # Mostrar contenedores actuales
            echo "Contenedores actuales:"
            sudo docker ps
            
            # Crear directorio si no existe
            mkdir -p ~/orders-canceler
            cd ~/orders-canceler
            
            # Detener contenedores existentes
            echo "Deteniendo contenedores existentes..."
            sudo docker-compose down || true
            sudo docker rm -f orders-canceler orders-db orders-grafana || true
            
            # Eliminar imágenes antiguas
            echo "Eliminando imágenes antiguas..."
            sudo docker rmi -f ${{ secrets.DOCKERHUB_USERNAME }}/orders-canceler:latest || true
            
            # Descargar imagen más reciente
            echo "Descargando imagen más reciente..."
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/orders-canceler:latest
            
            # Crear archivo application.properties para la aplicación
            cat > application.properties << EOL
            spring.datasource.url=${{ secrets.DB_URL }}
            spring.datasource.username=${{ secrets.DB_USERNAME }}
            spring.datasource.password=${{ secrets.DB_PASSWORD }}
            spring.datasource.driver-class-name=org.postgresql.Driver
            spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
            spring.jpa.hibernate.ddl-auto=none
            server.port=8080
            order.canceled.topic.arn=${{ secrets.ORDER_CANCELED_TOPIC_ARN }}
            EOL
            
            # Crear o actualizar docker-compose.yml
            echo "Creando docker-compose.yml..."
            cat > docker-compose.yml << EOL
            version: '3.8'
            
            services:
              orders-canceler:
                image: ${{ secrets.DOCKERHUB_USERNAME }}/orders-canceler:latest
                container_name: orders-canceler
                restart: always
                ports:
                  - "8080:8080"
                volumes:
                  - ./application.properties:/application.properties
                command: ["java", "-jar", "/app.jar", "--spring.config.location=file:/application.properties"]
                networks:
                  - orders-network
              
              postgres:
                image: postgres:14
                container_name: orders-db
                restart: always
                environment:
                  POSTGRES_DB: orders_db
                  POSTGRES_USER: ${{ secrets.DB_USERNAME }}
                  POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
                ports:
                  - "5432:5432"
                volumes:
                  - postgres-data:/var/lib/postgresql/data
                networks:
                  - orders-network
              
              grafana:
                image: grafana/grafana
                container_name: orders-grafana
                restart: always
                ports:
                  - "3000:3000"
                environment:
                  - GF_SECURITY_ADMIN_PASSWORD=${{ secrets.GRAFANA_PASSWORD }}
                  - GF_USERS_ALLOW_SIGN_UP=false
                  - GF_INSTALL_PLUGINS=grafana-postgresql-datasource
                volumes:
                  - grafana-data:/var/lib/grafana
                networks:
                  - orders-network
            
            volumes:
              postgres-data:
              grafana-data:
            
            networks:
              orders-network:
                driver: bridge
            EOL
            
            # Mostrar contenido del docker-compose.yml
            echo "Contenido de docker-compose.yml:"
            cat docker-compose.yml
            
            # Eliminar red existente si existe
            echo "Eliminando red existente si existe..."
            sudo docker network rm orders-network || true
            
            # Iniciar servicios
            echo "Iniciando servicios..."
            sudo docker-compose up -d --force-recreate
            
            # Esperar a que los contenedores estén en funcionamiento
            echo "Esperando a que los contenedores estén en funcionamiento..."
            sleep 10
            
            # Verificar estado de los contenedores
            echo "Estado de los contenedores:"
            sudo docker ps
            
            # Mostrar contenedores en ejecución
            echo "Contenedores en ejecución:"
            sudo docker ps
            
            # Mostrar logs del contenedor principal
            echo "Logs del contenedor orders-canceler:"
            sudo docker logs orders-canceler
            
            # Información de depuración
            echo "Información de depuración:"
            echo "Redes Docker:"
            sudo docker network ls
            echo "Volúmenes Docker:"
            sudo docker volume ls
            echo "Logs detallados del contenedor orders-canceler (últimas 50 líneas):"
            sudo docker logs orders-canceler --tail 50
